---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cifs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1G
  csi:
    driver: smb.csi.k8s.io
    volumeAttributes:
      source: //truenas.0.taranto.dev/k8s-demo-smb
    volumeHandle: cifs-demo
    nodeStageSecretRef:
      name: ktaranto-credentials
      namespace: k8s-demo
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
...
