---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: d-networking
    taranto.dev/tier: web
  name: d-web
spec:
  replicas: 1
  selector:
    matchLabels:
      taranto.dev/example: d-web
  template:
    metadata:
      labels:
        taranto.dev/tier: web
        taranto.dev/example: d-web
    spec:
      containers:
      - name: counter
        image: staranto/simple-http-counter:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8181
          name: http8181
        resources:
          requests: 
            cpu: "128m"
            memory: "256Mi"
          limits:
            cpu: "256m"
            memory: "384Mi"
        env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        livenessProbe:
          httpGet:
            path: /live
            port: 8282
          initialDelaySeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8282
          initialDelaySeconds: 3
      restartPolicy: Always
...
---
kind: Service
apiVersion: v1
metadata:
  name: d-web-svc
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: d-networking
spec:
  selector:
    taranto.dev/tier: web
  ports:
  - protocol: TCP
    port: 81
    targetPort: http8181
  type: LoadBalancer
...

