---
kind: Pod
apiVersion: v1
metadata:
  name: b-pod
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: b-storage
spec:
  containers:
  - name: b-one
    #image: staranto/k8s-demo-runner:1.2.6
    image: debian
    command: [ "sleep", "30000" ]
    imagePullPolicy: Always
    env:
    - name: KUBERNETES_NS
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    volumeDevices:
    - name: b-vol
      devicePath: "/dev/xvds"
  terminationGracePeriodSeconds: 1
  volumes:
    - name: b-vol
      persistentVolumeClaim:
        claimName: b-pvc
...
