---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-iscsi
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  iscsi:
     targetPortal: 192.168.86.2:3260
     iqn: iqn.2021-01.dev.taranto:iscsi
     lun: 1
     fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Block
...
