---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    mysidlabs.com/app: simple-http
    mysidlabs.com/app.simple-http.role: counter-route
  name: counter
spec:
  host: ""
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: counter
    weight: 100
  wildcardPolicy: None
...
