---
apiVersion: v1
kind: List
items:

- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: role-core
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/exec
    verbs:
    - get
    - list
    - create
    - delete

- apiVersion: rbac.authorization.k8s.io/v1  
  kind: RoleBinding
  metadata:
    name: c-sa-core-rolebinding
  roleRef:
    kind: Role
    apiGroup: rbac.authorization.k8s.io
    name: role-core
  subjects:
  - kind: ServiceAccount
    name: c-sa
...
