---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    taranto.dev/app: k8s-demo
  name: c-dep-katy
spec:
  replicas: 1
  selector:
    matchLabels:
      taranto.dev/app: c-dep
  template:
    metadata:
      labels:
        taranto.dev/app: c-dep
    spec:
      containers:
      - name: c-katy
        image: staranto/k8s-demo-user
        imagePullPolicy: Always
        command:
        - top
        securityContext:
          runAsUser: 3001
          runAsGroup: 3001
      - name: c-root
        image: staranto/k8s-demo-user
        imagePullPolicy: Always
        command:
        - top
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          privileged: true
      - name: c-none
        image: staranto/k8s-demo-user
        imagePullPolicy: Always
        command:
        - top
...

