---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    taranto.dev/app: k8s-demo
  name: c-dep-katy
spec:
  replicas: 1
  selector:
    matchLabels:
      taranto.dev/app: c-dep
  template:
    metadata:
      labels:
        taranto.dev/app: c-dep
    spec:
      containers:
      - name: c-one
        image: staranto/k8s-demo-user
        imagePullPolicy: IfNotPresent
        command:
        - top
      securityContext:
        runAsUser: 3001
        runAsGroup: 3001
        fsGroup: 3001
...
