---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    taranto.dev/app: k8s-demo
  name: c-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      taranto.dev/app: c-dep
  template:
    metadata:
      labels:
        taranto.dev/app: c-dep
    spec:
      containers:
      - command:
        - top
        image: staranto/user-demo
        name: c-one
...
