---
apiVersion: v1
kind: List
items:

- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: role-privileged
    namespace: staranto
  rules:
  - apiGroups:
    - security.openshift.io
    resources:
    - securitycontextconstraints
    resourceNames:
    - privileged
    verbs:
    - use

- apiVersion: rbac.authorization.k8s.io/v1  
  kind: RoleBinding
  metadata:
    name: c-sa-privileged-rolebinding
  roleRef:
    kind: Role
    apiGroup: rbac.authorization.k8s.io
    name: role-privileged
  subjects:
  - kind: ServiceAccount
    name: c-sa
...
