---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    mysidlabs.com/app: stress
    mysidlabs.com/app.stress.role: stress-route
  name: stress
spec:
  host: ""
  port:
    targetPort: svc80
  to:
    kind: Service
    name: stress
    weight: 100
  wildcardPolicy: None
...
