---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-1
  labels:
    taranto.dev/app: k8s-demo
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pv-1"
...
