apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: stress-k8s-demo.apps.k3sk.0.taranto.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stress
            port:
              number: 80
