---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
spec:
  selector:
    matchLabels:
      taranto.dev/app: stress
  template:
    metadata:
      labels:
        taranto.dev/app: stress
    spec:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: taranto.dev/app
              operator: in
              values:
              - stress
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: stress
        image: staranto/k8s-demo-runner:2.0.0-test
        imagePullPolicy: IfNotPresent
        command: [ "/run.sh", "stress" ]
        ports:
        - containerPort: 8080
          name: pod8080
        resources:
          requests: 
            cpu: "128m"
            memory: "128Mi"
          limits:
            cpu: "256m"
            memory: "256Mi"
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
  replicas: 1
...
---
apiVersion: v1
kind: Service
metadata:
  name: stress
  labels:
    taranto.dev/app: stress
spec:
  selector:
    taranto.dev/app: stress
  ports:
  - name: svc80
    port: 80
    targetPort: pod8080
...
