---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress
spec:
  selector:
    matchLabels:
      taranto.dev/app: stress
  template:
    metadata:
      labels:
        taranto.dev/app: stress
    spec:
      containers:
      - name: stress
        image: staranto/k8s-demo-runner:2.0.0-test
        imagePullPolicy: Always
        command: [ "/run.sh", "stress" ]
        ports:
        - containerPort: 8080
          name: pod8080
        resources:
          requests: 
            cpu: "128m"
            memory: "128Mi"
          limits:
            cpu: "256m"
            memory: "256Mi"
        env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      restartPolicy: Always
  replicas: 1
...
---
apiVersion: v1
kind: Service
metadata:
  name: stress
  labels:
    taranto.dev/app: stress
spec:
  selector:
    taranto.dev/app: stress
  ports:
  - name: svc80
    port: 80
    targetPort: pod8080
...
