apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: stress
spec:
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress
