apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: stress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress
  minReplicas: 1
  maxReplicas: 5 
  targetCPUUtilizationPercentage: 25
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 30
        periodSeconds: 20
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 20
        periodSeconds: 20
