---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
spec:
  containers:
  - name: mongodb
    image: mongo
    imagePullPolicy: Always
    securityContext:
      runAsUser: 999
      runAsGroup: 999
    ports:
    - containerPort: 27017
...
