---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      mysidlabs.com/app: tier2-node
  template:
    metadata:
      labels:
        mysidlabs.com/app: tier2-node
        mysidlabs.com/app.tier2-node.role: database
    spec:
      containers:
      - name: mongodb
        image: mongo
        imagePullPolicy: Always
        securityContext:
          runAsUser: 999
        ports:
        - containerPort: 27017
        #   name: mongo-port
        # resources:
        #   requests: 
        #     cpu: "128m"
        #     memory: "256Mi"
        #   limits:
        #     cpu: "256m"
        #     memory: "384Mi"
        # livenessProbe:
        #   httpGet:
        #     path: /live
        #     port: 8282
        #   initialDelaySeconds: 3
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 8282
        #   initialDelaySeconds: 3
      #   volumeMounts:
      #     - name: mongo-persistent-storage
      #       mountPath: /data/db
      # volumeClaimTemplates:
      #   - metadata:
      #       name: mongo-persistent-storage
      #     spec:
      #       storageClassName: "fast"
      #       accessModes: ["ReadWriteOnce"]
      #       resources:
      #         requests:
      #           storage: 1Gi
      restartPolicy: Always
  replicas: 1
...
---
apiVersion: v1
kind: Service
metadata:
  name: tier2-mongo
  labels:
    mysidlabs.com/app: tier2-node
    mysidlabs.com/app.tier2-node.role: mongo-service
spec:
  selector:
    mysidlabs.com/app.tier2-node.role: database
  ports:
  - name: mongo-port
    port: 27016
    targetPort: 27017 
...
