---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: b-ds
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: b-storage
spec:
  selector:
    matchLabels:
      taranto.dev/app: k8s-demo
  template:
    metadata:
      labels:
        taranto.dev/app: k8s-demo
    spec:
      containers:
      - name: b-one
        image: staranto/k8s-demo-runner:2.0.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: "/tmp"
            name: b-vol
      terminationGracePeriodSeconds: 1
      volumes:
        - name: b-vol
          persistentVolumeClaim:
            claimName: b-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
...
