---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: b-storage
  name: b-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      mysidlabs.com/app: b-dep
  template:
    metadata:
      labels:
        mysidlabs.com/app: b-dep
    spec:
      containers:
      - name: b-one
        image: mysidlabs/k8s-demo-runner:0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBERNETES_NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
          - mountPath: "/var/run/demo"
            name: b-vol
      volumes:
        - name: b-vol
          persistentVolumeClaim:
            claimName: b-pvc-dep        
...
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: b-pvc-dep
  annotations:
    volume.beta.kubernetes.io/storage-class: b-sc-nfs
    volume.beta.kubernetes.io/storage-provisioner: openshift.org/aws-efs
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 1Mi
  storageClassName: b-sc-nfs
  volumeMode: Filesystem
...
