---
apiVersion: v1
kind: Template
metadata:
  name: cpuhog-template
  annotations:
    description: "cpuhog load generator"
    tags: "ruby,demo"
objects:
- kind: Pod
  apiVersion: v1
  metadata:
    name: b-pod-${SEQ}
    labels:
      taranto.dev/app: k8s-demo
      taranto.dev/section: b-storage
  spec:
    containers:
    - name: b-one
      image: staranto/ks8-demo-runner:2.0.0
      imagePullPolicy: Always
      env:
      - name: KUBERNETES_NS
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      volumeMounts:
      - name: b-vol
        mountPath: "/tmp"
    terminationGracePeriodSeconds: 1
    volumes:
      - name: b-vol
        persistentVolumeClaim:
          claimName: b-pvc
parameters:
- description: Sequence
  name: SEQ
  value: seq
...
