---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: b-pv
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/b-pv

  # optional
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
#         - rock3
          - k3d-k3s-default-worker-1
...
