---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: x-pv
  labels:
    app: k8s-demo
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/x-pv"
...
