apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: counter-ingress
spec:
  rules:
    - host: "counter.apps.ocp4.mysidlabs.com"
      https:
        paths:
        - backend:
            serviceName: counter
            servicePort: 8181
