apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pounder
spec:
  maxReplicas: 8
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: pounder
  targetCPUUtilizationPercentage: 50
