---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pounder
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25% 
  template:
    metadata:
      labels:
        taranto.dev/app: simple-http
        taranto.dev/app.simple-http.role: pounder
      annotations:
        config: ""
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: pounder
        image: staranto/simple-http-pounder:latest
        imagePullPolicy: Always
        command:
        - /tmp/pounder
        - http://counter:8181
        - yellow
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","killall pounder; while killall -0 pounder; do sleep 1; done"]
        env:
        - name: COLOR
          valueFrom:
            configMapKeyRef:
              name: config-env
              key: COLOR
              optional: true
        - name: PROBE
          value: "1"
        - name: FAILCEILING
          value: "10240"
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        livenessProbe:
          httpGet:
            path: /live
            port: 8282
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3
        # resources:
        #   limits:
        #     memory: "64Mi"
        #     cpu: "200m"
        #   requests:
        #     memory: "32Mi"
        #     cpu: "100m"
...
