---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: a-cronjob
  labels:
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: a-core
spec:
  schedule: "*/3 * * * *"
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: a-one 
            image: mysidlabs/k8s-demo-runner:1.2.0
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 75m
                memory: 100Mi
              limits:
                cpu: 150m
                memory: 150Mi  
          restartPolicy: Never
          terminationGracePeriodSeconds: 1
...
