---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: a-ds
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: a-core
spec:
  selector:
    matchLabels:
      taranto.dev/app: k8s-demo
  template:
    metadata:
      labels:
        taranto.dev/app: k8s-demo
    spec:
      containers:
      - name: a-one
        image: staranto/k8s-demo-runner:2.0.0
        imagePullPolicy: Always
      terminationGracePeriodSeconds: 1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: taranto.dev/cpu
                operator: In
                values:
                - high
...
