---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: a-ds
  labels:
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: a-core
spec:
  selector:
    matchLabels:
      mysidlabs.com/app: k8s-demo
  template:
    metadata:
      labels:
        mysidlabs.com/app: k8s-demo
    spec:
      containers:
      - name: a-one
        image: mysidlabs/k8s-demo-runner:2.0.9
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: mysidlabs.com/cpu
                operator: In
                values:
                - high
...
