---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: a-core
  name: a-dep-multi
spec:
  replicas: 1
  selector:
    matchLabels:
      mysidlabs.com/app: a-dep-multi
  template:
    metadata:
      labels:
        mysidlabs.com/app: a-dep-multi
    spec:
      containers:
      - name: a-one
        image: mysidlabs/k8s-demo-runner:2.0.9
        imagePullPolicy: IfNotPresent
        env:
        - name: CID
          value: a-one
        volumeMounts:
        - name: common-dir
          mountPath: /tmp
      - name: a-two
        image: mysidlabs/k8s-demo-runner:2.0.9
        imagePullPolicy: IfNotPresent
        env:
        - name: CID
          value: a-two
        volumeMounts:
        - name: common-dir
          mountPath: /tmp
      - name: a-three
        image: mysidlabs/k8s-demo-runner:2.0.9
        imagePullPolicy: IfNotPresent
        env:
        - name: CID
          value: a-three
        volumeMounts:
        - name: common-dir
          mountPath: /tmp
      terminationGracePeriodSeconds: 1
      volumes:
      - name: common-dir
        emptyDir: {}
...
