---
apiVersion: batch/v1
kind: Job
metadata:
  name: a-job
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: a-core
spec:
  template:
    spec:
      containers:
      - name: a-one 
        image: staranto/k8s-demo-runner:latest
        imagePullPolicy: Always
      restartPolicy: Never
      terminationGracePeriodSeconds: 1
...

