---
apiVersion: batch/v1
kind: Job
metadata:
  name: a-job
  labels:
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: a-core
spec:
  template:
    spec:
      containers:
      - name: a-one 
        image: mysidlabs/k8s-demo-runner:0.1
        imagePullPolicy: Always
      restartPolicy: Never
      terminationGracePeriodSeconds: 1
...

