---
kind: Pod
apiVersion: v1
metadata:
  name: a-pod
  labels:
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: a-core
spec:
  containers:
    - name: a-one
      image: mysidlabs/k8s-demo-runner:2.0.9
      env:
      - name: CID
        value: a-one
      volumeMounts:
      - name: common-dir
        mountPath: /tmp
    - name: a-two
      image: mysidlabs/k8s-demo-runner:2.0.9
      env:
      - name: CID
        value: a-two
      volumeMounts:
      - name: common-dir
        mountPath: /tmp
  terminationGracePeriodSeconds: 1
  volumes:
  - name: common-dir
    emptyDir: {}
...
