---
kind: Pod
apiVersion: v1
metadata:
  name: a-pod
  labels:
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: a-core
spec:
  containers:
  - name: a-one
    image: mysidlabs/k8s-demo-runner:1.1.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 75m
        memory: 100Mi
      limits:
        cpu: 150m
        memory: 150Mi
terminationGracePeriodSeconds: 1
...
