---
kind: Pod
apiVersion: v1
metadata:
  name: a-pod
  labels:
    taranto.dev/app: k8s-demo
spec:
  terminationGracePeriodSeconds: 1
  containers:
    - name: a-one
      image: bash
      command: [ "watch", "uptime" ]
...
