---
kind: Pod
apiVersion: v1
metadata:
  name: a-pod
  labels:
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: a-core
spec:
  containers:
  - name: a-one
    image: mysidlabs/k8s-demo-runner:2.0.9 
    imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 1
...
