---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: a-rs
  labels:
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: a-core
spec:
  replicas: 3
  selector:
    matchLabels:
      mysidlabs.com/example: a-replicaset
  template:
    metadata:
      labels:
        mysidlabs.com/example: a-replicaset
    spec:
      containers:
      - name: a-one
        image: mysidlabs/k8s-demo-runner:0.2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 75m
            memory: 100Mi
          limits:
            cpu: 150m
            memory: 150Mi
      terminationGracePeriodSeconds: 1
...
