---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: a-rs
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: a-core
spec:
  replicas: 3
  selector:
    matchLabels:
      taranto.dev/example: a-replicaset
  template:
    metadata:
      labels:
        taranto.dev/example: a-replicaset
    spec:
      containers:
      - name: a-one
        image: staranto/k8s-demo-runner:2.0.0
        imagePullPolicy: Always
      terminationGracePeriodSeconds: 1
...
