---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: a-stateful
  labels:
    mysidlabs.com/app: k8s-demo
    mysidlabs.com/section: a-core
spec:
  replicas: 2
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      mysidlabs.com/example: a-dep
  template:
    metadata:
      labels:
        mysidlabs.com/example: a-dep
    spec:
      containers:
      - name: a-one
        image: mysidlabs/k8s-demo-runner:2.0.9
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 1
...
